#include "glfw_example.h"

const char* phong_vs_src =
    "uniform mat4 model;"
    "uniform mat4 view;"
    "uniform mat4 proj;"
    "uniform mat4 normalMat;"
    "uniform vec3 ambientCol;"
    "uniform vec3 diffuseCol;"
    "uniform vec3 specularCol;"
    "uniform vec3 lightPos;"
    "uniform float shininess;"
    "attribute vec3 position;"
    "attribute vec3 normal;"
    "varying vec3 vNormal;"
    "varying vec3 vEyePos;"
    "varying vec3 vLightPos;"
    ""
    "vec3 surfaceNormal(vec3 normal, mat4 normalMat) {"
    "  return normalize((normalMat * vec4(normal, 0.0)).xyz);"
    "}"
    ""
    "void main(){"
    "  vec4 worldPos = model * vec4(position, 1.0);"
    "  vec4 eyePos = view * worldPos;"
    "  vEyePos = eyePos.xyz;"
    "  vNormal = surfaceNormal(normalize(normal), normalMat);"
    "  vLightPos = (view * vec4(lightPos, 1.0)).xyz;"
    "  gl_Position = proj * eyePos;"
    "}";

const char* phong_fs_src =
#ifdef __EMSCRIPTEN__
    "precision highp float;"
#endif
    "uniform mat4 model;"
    "uniform mat4 view;"
    "uniform mat4 proj;"
    "uniform mat4 normalMat;"
    "uniform vec3 ambientCol;"
    "uniform vec3 diffuseCol;"
    "uniform vec3 specularCol;"
    "uniform vec3 lightPos;"
    "uniform float shininess;"
    "varying vec3 vNormal;"
    "varying vec3 vEyePos;"
    "varying vec3 vLightPos;"
    ""
    "float phong(vec3 lightDir, vec3 eyeDir, vec3 surfaceNormal) {"
    "  return dot(reflect(-lightDir, surfaceNormal), eyeDir);"
    "}"
    ""
    "void main() {"
    "  vec3 L = normalize(vLightPos - vEyePos);"
    "  vec3 E = normalize(-vEyePos);"
    "  vec3 N = normalize(vNormal);"
    ""
    "  float NdotL = max(0.0, dot(N, L));"
    "  vec3 color = ambientCol + NdotL * diffuseCol;"
    ""
    "  float specular = phong(L, E, N);"
    "  color += max(pow(specular, shininess), 0.0) * specularCol;"
    "  gl_FragColor = vec4(color, 1.0);"
    "}";
