#!/bin/sh

readonly target=${1:-test_asan}
readonly config=${2:-release}
readonly qualifier=${3:-sse}
readonly profile=${config}_${qualifier}

retest() {
    printf "\033c"
    echo "----------------------------------------"
    date +%Y-%m-%d-%H:%M:%S
    echo "----------------------------------------"
    make -j3 config=$2_$3 $1 && bin/$2/$1;
}

make verbose=1 config=$profile clean
retest $target $config $qualifier

export -f retest
fswatch -o src test | xargs -n1 -I{} bash -c "retest $target $config $qualifier" _ {}
