#!/bin/sh

# compile with SIMD:
# ./compile.sh -asd

FILES="src/data/cons.c src/data/consrc.c src/data/hashset.c src/data/hashtable.c src/data/object.c src/data/octree.c src/data/quadtree.c src/geom/circle.c src/geom/halfedge.c src/geom/isec.c src/geom/quadedge.c src/geom/triangle.c src/math/math.c src/math/hashfn.c src/math/vec.c src/mem/mpool.c"
TESTS=
CFLAGS="-std=c11 -Os -Isrc"
EMFLAGS="-s ASM_JS=1 -s ASSERTIONS=0 -s INVOKE_RUN=0 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s MODULARIZE=1 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY='48*1024*1024'"
OUT=geom.js

usage()
{
    cat <<EOF
Usage:
  -a     : separate asm.js output
  -c     : enable Closure compiler step
  -d     : remove duplicate functions
  -D SYM : add define
  -h     : show this help
  -k     : enable runtime checks
  -s     : enable SSE (SIMD.js)
  -t     : include tests
EOF
    exit 1
}

while getopts acdhkstD: opt; do
    case $opt in
        s) CFLAGS="$CFLAGS -DCT_FEATURE_SSE -fslp-vectorize -msse2"
           EMFLAGS="$EMFLAGS -s SIMD=1"
           ;;
        a) EMFLAGS="$EMFLAGS --separate-asm"
           ;;
        c) EMFLAGS="$EMFLAGS --closure 1"
           ;;
        d) EMFLAGS="$EMFLAGS -s ELIMINATE_DUPLICATE_FUNCTIONS=1"
           # EMFLAGS="$EMFLAGS -s ELIMINATE_DUPLICATE_FUNCTIONS_PASSES=5"
           EMFLAGS="$EMFLAGS -s ELIMINATE_DUPLICATE_FUNCTIONS_DUMP_EQUIVALENT_FUNCTIONS=1"
           ;;
        k) CFLAGS="$CFLAGS -DCT_FEATURE_CHECKS"
           ;;
        D) CFLAGS="$CFLAGS -D$OPTARG"
           ;;
        t) CFLAGS="$CFLAGS -DNDEBUG -DCT_FEATURE_LOG"
           TESTS="src/common/test.c test/main.c test/circle.c test/cons.c test/consrc.c test/hash.c test/hashset.c test/hashtable.c test/mpool.c test/octree.c test/quadtree.c test/qedge.c test/vec.c"
           ;;
        h) usage
           ;;
        \?) echo "invalid option: $opt" >&2
            usage
            exit 1
            ;;
        :) echo "$opt missing argument" >&2
           usage
           exit 1
           ;;
    esac
done

echo "cflags: $CFLAGS"
echo "emflags: $EMFLAGS"

emcc $CFLAGS \
     --memory-init-file 0 \
     --emit-symbol-map \
     $EMFLAGS \
     -s "TOTAL_STACK=1*1024*1024" \
     -s "EXPORT_NAME='geom'" \
     -o $OUT \
     $FILES \
     $TESTS

ls -la $OUT
cp $OUT geom-cljs/resources/public/js/

# -s EXPORTED_FUNCTIONS=@exports.json
# -s ELIMINATE_DUPLICATE_FUNCTIONS_DUMP_EQUIVALENT_FUNCTIONS=1
