#!/bin/sh
for i in `ls assets/$1*.svg`; do
    echo "converting $i"
    rsvg-convert -b "#fff" -f png -o $i.png $i
done
ffmpeg \
    -framerate 30 \
    -i assets/$1-%04d.svg.png \
    -s:v 600x600 \
    -c:v libx264 \
    -profile:v high \
    -crf 23 \
    -pix_fmt yuv420p \
    -y \
    out.mp4
